---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - У сайта должна быть возможность просмотреть продолжение описания товара,в карточке товара 
  - Пользователь должен иметь возможность видеть название в первом пункте во вкладке 'category'
  - Пользователь должен иметь возможность регистрации 
  - Пользователь должен иметь возможность давать обратную связь
  - У сайта должна быть опция названий в корзине (наименование товара,id,количество,цена)
  - Пользователь должен иметь возможность подтверждения товара в корзину, при добавление товара в корзину
  - Пользователь должен иметь возможность получения уведомлений и писем для пользователей
